##############################
#                            #
# Spotify Configuration File #
#                            #
##############################

behavior:

  seek_milliseconds: 5000
  volume_increment: 5
  tick_rate_milliseconds: 250

  enable_text_emphasis: true
  show_loading_indicator: true
  enforce_wide_search_bar: false
  set_window_title: false
  
  liked_icon: â™¥
  shuffle_icon: ï´
  repeat_track_icon: ğŸ”‚
  repeat_context_icon:  ï¥ğŸ”
  playing_icon: ï‹
  paused_icon: â¸ïŒ
 
keybindings:
 
  manage_devices:  "d" 
  help:            "?"

  back:  "ctrl-q"

  jump_to_album:          "a"
  jump_to_artist_album:   "A"
  jump_to_context:        "o"
  add_item_to_queue:      "z"

  decrease_volume:  "-"
  increase_volume:  "="
  
  toggle_playback:  " "
  seek_backwards:   "<"
  seek_forwards:    ">"
  next_track:       "n"
  previous_track:   "p"
  
  copy_song_url:    "c"
  copy_album_url:   "C"
  
  shuffle:  "ctrl-s"
  repeat:   "r"
  search:   "/"
  
  audio_analysis:   "v"
  basic_view:       "B"
